# Generated by Django 4.0.4 on 2023-03-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('logo', models.ImageField(blank=True, upload_to='upload')),
                ('status', models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
